site_name: Core2 framework
site_url: https://n2ref.github.io/core2-docs
repo_name: Core2
repo_url: https://github.com/n2ref/core2
theme:
  name: material
  language: ru
  favicon: favicon.ico
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_javascript:
  - assets/js/highlight.min.js
  - assets/js/main.js
extra_css:
  - assets/css/extra.css
  - assets/css/highlight.min.css
plugins:
  - search:
      lang: ru
  - offline:
  - glightbox
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Введение:    index.md
  - Установка и настройка:
    - Установка:   setup/install.md
    - Настройка:
        - Пользователи и роли: setup/settings/users_roles.md
        - Управление модулями: setup/settings/modules.md
        - Конфиги:             setup/settings/config.md
    - Внешний вид: setup/themes.md
  - Структура фреймворка:
      - Классы:
        - Db:        framework/classes/db.md
        - Acl:       framework/classes/acl.md
        - Log:       framework/classes/log.md
        - Cache:     framework/classes/cache.md
        - Tool:      framework/classes/tool.md
        - Templater: framework/classes/templater.md
        - Common:    framework/classes/common.md
        - CommonApi: framework/classes/common_api.md
        - Panel:     framework/classes/panel.md
        - Tabs:      framework/classes/tabs.md
        - Edit:      framework/classes/edit.md
        - Table:     framework/classes/table.md
      - Интерфейсы: framework/interfaces.md
      - Поля формы:
          - Обзор: framework/edit/index.md
          - Hidden: framework/edit/hidden.md
          - Protect: framework/edit/protect.md
          - Custom: framework/edit/custom.md
          - Text: framework/edit/text.md
          - Edit: framework/edit/edit.md
          - Time: framework/edit/time.md
          - Datetime local: framework/edit/datetime_local.md
          - Date week: framework/edit/date_week.md
          - Date month: framework/edit/date_month.md
          - Number: framework/edit/number.md
          - Number range: framework/edit/number_range.md
          - Money: framework/edit/money.md
          - File: framework/edit/file.md
          - Link: framework/edit/link.md
          - Search: framework/edit/search.md
          - Date: framework/edit/date.md
          - Datetime: framework/edit/datetime.md
          - Color: framework/edit/color.md
          - Coordinates: framework/edit/coordinates.md
          - Switch: framework/edit/switch.md
          - Combobox: framework/edit/combobox.md
          - Date2: framework/edit/date2.md
          - Datetime2: framework/edit/datetime2.md
          - Modal2: framework/edit/modal2.md
          - Modal list: framework/edit/modal_list.md
          - Daterange: framework/edit/daterange.md
          - Password: framework/edit/password.md
          - Textarea: framework/edit/textarea.md
          - Fck*: framework/edit/fck.md
          - Radio: framework/edit/radio.md
          - Radio2: framework/edit/radio2.md
          - Checkbox: framework/edit/checkbox.md
          - Checkbox2: framework/edit/checkbox2.md
          - Select: framework/edit/select.md
          - List: framework/edit/list.md
          - List hidden: framework/edit/list_hidden.md
          - Multilist: framework/edit/multilist.md
          - Select2: framework/edit/select2.md
          - Multiselect2: framework/edit/multiselect2.md
          - Tags: framework/edit/tags.md
          - Multilist2: framework/edit/multilist2.md
          - Multilist3: framework/edit/multilist3.md
          - Dataset: framework/edit/dataset.md
          - XFile: framework/edit/xfile.md
          - XFiles: framework/edit/xfiles.md
          - Modal: framework/edit/modal.md
      - Системные модули:
        - Обзор:      framework/modules/review.md
        - Admin:      framework/modules/admin.md
        - Cron:       framework/modules/cron.md
        - Profile:    framework/modules/profile.md
        - Queue:      framework/modules/queue.md
        - Webservice: framework/modules/webservice.md
  - Структура модулей:
    - Обзор:                modules/review.md
    - Контроллер:           modules/controller.md
    - Обработка сохранения: modules/handler.md
    - Командная строка cli: modules/cli.md
    - Модели таблиц:        modules/models.md
    - Установка:            modules/install.md
    - Конфиг:               modules/config.md
    - REST запросы:         modules/rest.md
  - Best practice:
    - Стили написания кода:
      - Паттерны проектирования: best_practice/style/patterns.md
      - База данных:             best_practice/style/database.md
      - PSR:                     best_practice/style/psr.md
    - Модули:
      - Модели таблиц:        best_practice/module/model.md
      - Классы:               best_practice/module/classes.md
      - Скрипты для браузера: best_practice/module/scripts.md
      - Контроллер:           best_practice/module/controller.md
  - Другое:
    - Тестирование: other/tests.md
    - Переводы:     other/translations.md
    - Документация: other/docs.md